# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('esal', models.FloatField()),
                ('Eaddr', models.CharField(max_length=100)),
                ('ephno', models.BigIntegerField()),
            ],
        ),
    ]
